// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT6bw7pmU0U_LPCnvfYS9RXxQNvyomBlU',
    appId: '1:40717949917:web:9068d26ea85c7439aaf434',
    messagingSenderId: '40717949917',
    projectId: 'inventory-app-aftongoulding',
    authDomain: 'inventory-app-aftongoulding.firebaseapp.com',
    storageBucket: 'inventory-app-aftongoulding.firebasestorage.app',
    measurementId: 'G-2RDB88P4N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKrbDPu5z3gvqk2L-sCyiLgT3ZAht-_-Y',
    appId: '1:40717949917:android:74684027ff0d32e8aaf434',
    messagingSenderId: '40717949917',
    projectId: 'inventory-app-aftongoulding',
    storageBucket: 'inventory-app-aftongoulding.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHOtdJ8e5-igOW9k1EpfSg5jiNvJWLato',
    appId: '1:40717949917:ios:0a2ed7319c284d14aaf434',
    messagingSenderId: '40717949917',
    projectId: 'inventory-app-aftongoulding',
    storageBucket: 'inventory-app-aftongoulding.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHOtdJ8e5-igOW9k1EpfSg5jiNvJWLato',
    appId: '1:40717949917:ios:0a2ed7319c284d14aaf434',
    messagingSenderId: '40717949917',
    projectId: 'inventory-app-aftongoulding',
    storageBucket: 'inventory-app-aftongoulding.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT6bw7pmU0U_LPCnvfYS9RXxQNvyomBlU',
    appId: '1:40717949917:web:664df422a87200dfaaf434',
    messagingSenderId: '40717949917',
    projectId: 'inventory-app-aftongoulding',
    authDomain: 'inventory-app-aftongoulding.firebaseapp.com',
    storageBucket: 'inventory-app-aftongoulding.firebasestorage.app',
    measurementId: 'G-NTLV8WPJRJ',
  );
}
